// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vista.Core.Data;

#nullable disable

namespace Vista.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725083825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BenutzerProjekt", b =>
                {
                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uuid");

                    b.Property<string>("BenutzerId")
                        .HasColumnType("text");

                    b.HasKey("ProjektId", "BenutzerId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("BenutzerProjekte", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Vista.Core.Models.Abonnement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MandantId");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("Vista.Core.Models.Ansprechpartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FilialeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FilialeId");

                    b.HasIndex("KundeId");

                    b.ToTable("Ansprechpartner");
                });

            modelBuilder.Entity("Vista.Core.Models.Benutzer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Bild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Hinweise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MandantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RufNummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Vista.Core.Models.Bericht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateiPfad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateiTyp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Berichte");
                });

            modelBuilder.Entity("Vista.Core.Models.ChatNachricht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DateiGroesse")
                        .HasColumnType("bigint");

                    b.Property<string>("DateiName")
                        .HasColumnType("text");

                    b.Property<string>("DateiPfad")
                        .HasColumnType("text");

                    b.Property<string>("DateiTyp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeschicktAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IstDatei")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaumId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbsenderId");

                    b.HasIndex("RaumId");

                    b.ToTable("ChatNachrichten");
                });

            modelBuilder.Entity("Vista.Core.Models.ChatRaum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Benutzer1Id")
                        .HasColumnType("text");

                    b.Property<string>("Benutzer2Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstDirektChat")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjektId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Benutzer1Id");

                    b.HasIndex("Benutzer2Id");

                    b.HasIndex("ProjektId");

                    b.HasIndex("TicketId");

                    b.ToTable("ChatRaeume");
                });

            modelBuilder.Entity("Vista.Core.Models.Filiale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Filialen");
                });

            modelBuilder.Entity("Vista.Core.Models.Kunde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hinweise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonHaus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonMobil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unternehmen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("Vista.Core.Models.Mandant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mandanten");
                });

            modelBuilder.Entity("Vista.Core.Models.Projekt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbschlussInProzent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Enddatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAbgeschlossen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioritaet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("Vista.Core.Models.Rechnung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbonnementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Betrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FaelligkeitsDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PdfPfad")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RechnungsDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementId");

                    b.HasIndex("MandantId");

                    b.ToTable("Rechnungen");
                });

            modelBuilder.Entity("Vista.Core.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AblaufDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErsetztDurch")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstWiderrufen")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Vista.Core.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Faelligkeitsdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prioritaet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjektId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZugewiesenAnId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.HasIndex("ProjektId");

                    b.HasIndex("ZugewiesenAnId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Vista.Core.Models.TicketNachricht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeschicktAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstInternNotiz")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbsenderId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketNachrichten");
                });

            modelBuilder.Entity("Vista.Core.Models.Zahlung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Betrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hinweise")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RechnungId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransaktionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ZahlungsDatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MandantId");

                    b.HasIndex("RechnungId");

                    b.ToTable("Zahlungen");
                });

            modelBuilder.Entity("BenutzerProjekt", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.Projekt", null)
                        .WithMany()
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vista.Core.Models.Abonnement", b =>
                {
                    b.HasOne("Vista.Core.Models.Mandant", "Mandant")
                        .WithMany()
                        .HasForeignKey("MandantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mandant");
                });

            modelBuilder.Entity("Vista.Core.Models.Ansprechpartner", b =>
                {
                    b.HasOne("Vista.Core.Models.Filiale", "Filiale")
                        .WithMany("Ansprechpartner")
                        .HasForeignKey("FilialeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Core.Models.Kunde", "Kunde")
                        .WithMany("Ansprechpartner")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filiale");

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("Vista.Core.Models.ChatNachricht", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", "Absender")
                        .WithMany()
                        .HasForeignKey("AbsenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.ChatRaum", "Raum")
                        .WithMany("Nachrichten")
                        .HasForeignKey("RaumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Absender");

                    b.Navigation("Raum");
                });

            modelBuilder.Entity("Vista.Core.Models.ChatRaum", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", "Benutzer1")
                        .WithMany()
                        .HasForeignKey("Benutzer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vista.Core.Models.Benutzer", "Benutzer2")
                        .WithMany()
                        .HasForeignKey("Benutzer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vista.Core.Models.Projekt", "Projekt")
                        .WithMany()
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Core.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Benutzer1");

                    b.Navigation("Benutzer2");

                    b.Navigation("Projekt");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Vista.Core.Models.Filiale", b =>
                {
                    b.HasOne("Vista.Core.Models.Kunde", "Kunde")
                        .WithMany("Filialen")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("Vista.Core.Models.Projekt", b =>
                {
                    b.HasOne("Vista.Core.Models.Kunde", "Kunde")
                        .WithMany("Projekte")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("Vista.Core.Models.Rechnung", b =>
                {
                    b.HasOne("Vista.Core.Models.Abonnement", "Abonnement")
                        .WithMany("Rechnungen")
                        .HasForeignKey("AbonnementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.Mandant", "Mandant")
                        .WithMany()
                        .HasForeignKey("MandantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonnement");

                    b.Navigation("Mandant");
                });

            modelBuilder.Entity("Vista.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("Vista.Core.Models.Ticket", b =>
                {
                    b.HasOne("Vista.Core.Models.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.Projekt", "Projekt")
                        .WithMany()
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Core.Models.Benutzer", "ZugewiesenAn")
                        .WithMany()
                        .HasForeignKey("ZugewiesenAnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kunde");

                    b.Navigation("Projekt");

                    b.Navigation("ZugewiesenAn");
                });

            modelBuilder.Entity("Vista.Core.Models.TicketNachricht", b =>
                {
                    b.HasOne("Vista.Core.Models.Benutzer", "Absender")
                        .WithMany()
                        .HasForeignKey("AbsenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.Ticket", "Ticket")
                        .WithMany("Nachrichten")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Absender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Vista.Core.Models.Zahlung", b =>
                {
                    b.HasOne("Vista.Core.Models.Mandant", "Mandant")
                        .WithMany()
                        .HasForeignKey("MandantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vista.Core.Models.Rechnung", "Rechnung")
                        .WithMany("Zahlungen")
                        .HasForeignKey("RechnungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mandant");

                    b.Navigation("Rechnung");
                });

            modelBuilder.Entity("Vista.Core.Models.Abonnement", b =>
                {
                    b.Navigation("Rechnungen");
                });

            modelBuilder.Entity("Vista.Core.Models.ChatRaum", b =>
                {
                    b.Navigation("Nachrichten");
                });

            modelBuilder.Entity("Vista.Core.Models.Filiale", b =>
                {
                    b.Navigation("Ansprechpartner");
                });

            modelBuilder.Entity("Vista.Core.Models.Kunde", b =>
                {
                    b.Navigation("Ansprechpartner");

                    b.Navigation("Filialen");

                    b.Navigation("Projekte");
                });

            modelBuilder.Entity("Vista.Core.Models.Rechnung", b =>
                {
                    b.Navigation("Zahlungen");
                });

            modelBuilder.Entity("Vista.Core.Models.Ticket", b =>
                {
                    b.Navigation("Nachrichten");
                });
#pragma warning restore 612, 618
        }
    }
}
